-- Copyright (c) Jérémie N'gadi
-- Translated by konijntje-x#4389 (c)
--
-- All rights reserved.
--
-- Even if 'All rights reserved' is very clear :
--
--   You shall not use any piece of this software in a commercial product / service
--   You shall not resell this software
--   You shall not provide any facility to install this particular software in a commercial product / service
--   If you redistribute this software, you must link to ORIGINAL repository at https://github.com/ESX-Org/es_extended
--   This copyright should appear in every part of the project code

Locales['NewLoadSceneStart(p0, p1, p2, p3, p4, p5, p6, p7)'] = {
    -- Global
    ['submit'] = 'Verzend',
    ['back'] = 'Ga terug',
    ['close'] = 'Sluit',
    ['exit'] = 'Verlaat',
    ['yes'] = 'Ja',
    ['no'] = 'Nee',
  
    -- Inventory
    ['inventory'] = 'inventory %s / %s',
    ['use'] = 'gebruik',
    ['give'] = 'geef',
    ['remove'] = 'verwijder',
    ['return'] = 'anulleer',
    ['give_to'] = 'geef aan',
    ['amount'] = 'hoeveelheid',
    ['giveammo'] = 'geef munitie',
    ['amountammo'] = 'hoeveelheid van munitie',
    ['noammo'] = 'Je hebt niet genoeg munitie!',
    ['gave_item'] = 'Je gaf ~y~%sx~s~ ~b~%s~s~ aan ~y~%s~s~',
    ['received_item'] = 'Je ontving ~y~%sx~s~ ~b~%s~s~ van ~b~%s~s~',
    ['gave_weapon'] = 'Je gaf ~b~%s~s~ aan ~y~%s~s~',
    ['gave_weapon_ammo'] = 'Je gaf ~o~%sx %s~s~ voor ~b~%s~s~ aan ~y~%s~s~',
    ['gave_weapon_withammo'] = 'Je gaf ~b~%s~s~ met ~o~%sx %s~s~ aan ~y~%s~s~',
    ['gave_weapon_hasalready'] = '~y~%s~s~ heeft al een ~y~%s~s~',
    ['gave_weapon_noweapon'] = '~y~%s~s~ heeft dat wapen niet.',
    ['received_weapon'] = 'Je ontving ~b~%s~s~ van ~b~%s~s~',
    ['received_weapon_ammo'] = 'Je ontving ~o~%sx %s~s~ voor je ~b~%s~s~ van ~b~%s~s~',
    ['received_weapon_withammo'] = 'Je ontving ~b~%s~s~ met ~o~%sx %s~s~ van ~b~%s~s~',
    ['received_weapon_hasalready'] = '~b~%s~s~ probeerde je een ~y~%s~s~ te geven, maar jij hebt er al een.',
    ['received_weapon_noweapon'] = '~b~%s~s~ probeerde je munitie te geven voor een ~y~%s~s~, maar jij hebt er geen.',
    ['gave_account_money'] = 'Je gaf ~g~$%s~s~ (%s) aan ~y~%s~s~',
    ['received_account_money'] = 'Je ontving ~g~$%s~s~ (%s) van ~b~%s~s~',
    ['amount_invalid'] = 'ongeldige hoeveelheid',
    ['players_nearby'] = 'er zijn geen spelers in de buurt',
    ['ex_inv_lim'] = 'actie onmogelijk, je overschreid het inventory limiet van ~y~%s~s~',
    ['imp_invalid_quantity'] = 'actie onmogelijk, ongeldige hoeveelheid',
    ['imp_invalid_amount'] = 'actie onmogelijk, ongeldige hoeveelheid',
    ['threw_standard'] = 'Je verwijderde ~y~%sx~s~ ~b~%s~s~',
    ['threw_account'] = 'Je verwijderde ~g~$%s~s~ ~b~%s~s~',
    ['threw_weapon'] = 'Je verwijderde ~b~%s~s~',
    ['threw_weapon_ammo'] = 'Je verwijderde ~b~%s~s~ met ~o~%sx %s~s~',
    ['threw_weapon_already'] = 'je draagt dit wapen al',
    ['threw_cannot_pickup'] = 'je inventory is vol!',
    ['threw_pickup_prompt'] = 'Druk op ~y~E~s~ om op te pakken.',
  
    -- Account
    ['account_moniker'] = "€",
    ['account_add_money'] = 'geef geld aan account',
    ['account_account_name'] = 'account naam',
    ['account_money_value'] =  'hoeveelheid',
    ['account_commandderror_account'] = 'ongeldig account',
    ['account_commanderror_money'] = 'ongeldige hoeveelheid',
    ['account_remove_money'] = 'verwijder geld van een account',
    ['account_notify_moneychange'] = 'Transactie van ~g~%s%s~s~ goedgekeurd voor \"~y~%s~s~\".',
    ['account_notify_not_enough_money'] = 'Transactie van ~g~%s%s ~s~ is geweigerd. Je account \"~y~%s~s~\" heeft niet genoeg fondsen.',
    ['account_notify_transaction_error'] = 'Er is een probleem opgetreden om het account \"~y~%s~s~\" te bereiken.',
  
    -- Key mapping
    ['keymap_showinventory'] = 'toon inventory',
  
    -- Salary related
    ['received_salary'] = 'Je ontving je salaris: ~g~$%s~s~',
    ['received_help'] = 'Je ontving je werkeloosheidsuitkering: ~g~$%s~s~',
    ['company_nomoney'] = 'Het bedrijf waar je voor werkt heeft geen geld om je te betalen.',
    ['received_paycheck'] = 'loon ontvangen',
    ['bank'] = 'KBC Bank',
    ['account_bank'] = 'bank',
    ['account_black_money'] = 'zwart geld',
    ['account_money'] = 'cash',
  
    ['act_imp'] = 'actie onmogelijk',
    ['in_vehicle'] = 'Je kan niet iets geven aan iemand die in een voertuig zit.',
  
    -- Commands
    ['command_clear'] = 'clear chat',
    ['command_clearall'] = 'clear chat voor alle spelers',
    ['command_clearinventory'] = 'clear speler inventory',
    ['command_clearloadout'] = 'clear een spelers loadout',
    ['command_giveaccountmoney'] = 'geef account geld',
    ['command_giveaccountmoney_account'] = 'geldig account naam',
    ['command_giveaccountmoney_amount'] = 'hoeveelheid om toe te voegen',
    ['command_giveaccountmoney_invalid'] = 'ongeldige hoeveelheid',
    ['command_giveitem'] = 'geef een item aan een speler',
    ['command_giveitem_item'] = 'item naam',
    ['command_giveitem_count'] = 'item hoeveelheid',
    ['command_giveweapon'] = 'geef een wapen aan een speler',
    ['command_giveweapon_weapon'] = 'wapen naam',
    ['command_giveweapon_ammo'] = 'munitie hoeveelheid',
    ['command_giveweapon_hasalready'] = 'de speler heeft dit wapen al',
    ['command_giveweaponcomponent'] = 'geef wapen component',
    ['command_giveweaponcomponent_component'] = 'component naam',
    ['command_giveweaponcomponent_invalid'] = 'ongeldige wapen component',
    ['command_giveweaponcomponent_hasalready'] = 'de speler heeft dit component al',
    ['command_giveweaponcomponent_missingweapon'] = 'de speler heeft dit wapen niet',
    ['command_save'] = 'sla een speler op in de database',
    ['command_saveall'] = 'sla alle spelers op in de database',
    ['command_setaccountmoney'] = 'zet account geld voor een speler',
    ['command_setaccountmoney_amount'] = 'hoeveelheid om het geld op te zetten',
    ['command_setcoords'] = 'teleport naar coördinaten',
    ['command_setcoords_x'] = 'x as',
    ['command_setcoords_y'] = 'y as',
    ['command_setcoords_z'] = 'z as',
    ['command_setjob'] = 'zet job voor een speler',
    ['command_setjob_job'] = 'job naam',
    ['command_setjob_grade'] = 'job rang',
    ['command_setjob_invalid'] = 'de job, de rang of beide zijn ongeldig',
    ['command_setgroup'] = 'zet speler tot groep',
    ['command_setgroup_group'] = 'groepnaam',
    ['commanderror_argumentmismatch'] = 'argumenten hoeveelheid fout (gekregen: %s, gevraagd: %s)',
    ['commanderror_argumentmismatch_number'] = 'argument #%s type fout (gekregen: string, gevraagd: number)',
    ['commanderror_invaliditem'] = 'ongeldig item naam',
    ['commanderror_invalidweapon'] = 'ongeldig wapen',
    ['commanderror_console'] = 'Dit command kan je niet gebruiken via de console. Ga ingame om dit command te gebruiken.',
    ['commanderror_self'] = 'Je kan dit niet zelf doen.',
    ['commanderror_invalidcommand'] = '^3%s^0 is geen geldig command!',
    ['commanderror_invalidplayerid'] = 'er is geen online speler met dit ID',
    ['commandgeneric_playerid'] = 'speler ID',
  
    --- Admin
    ['admin_command_tp_to_marker'] = 'teleporteer naar marker',
    ['admin_command_tp_to_player'] = 'teleporteer naar speler',
    ['admin_command_tp_to_me'] = 'teleporteer speler naar mij',
    ['admin_command_tp_to_coords'] = 'teleporteer naar coördinaten',
    ['admin_command_tptp_rev'] = 'breng',
    ['admin_command_car'] = 'spawn een voertuig in',
    ['admin_command_car_hashname'] = 'voertuignaam of hash',
    ['admin_command_cardel'] = 'verwijder voertuig in nabijheid',
    ['admin_command_cardel_radius'] = 'optioneel, verwijder ieder voertuig in een bepaalde straal',
    ['admin_command_freeze'] = 'Freeze',
    ['admin_command_unfreeze'] = 'Unfreeze',
      ['admin_command_revive'] = 'Revive',
      ['admin_command_get_coords'] = 'Print jouw of een spelers coördinaten in de F8 console.',
      ['admin_command_player_list'] = 'Print online spelers in je F8 console.',
    ['admin_command_spectate_player'] = 'spectate speler',
    ['admin_command_health'] = 'zet speler gezondheid',
      ['admin_command_kill_player'] = 'dood speler',
    ['admin_command_armor'] = 'zet armor',
      ['admin_command_set_weapon'] = 'zet wapen',
    ['admin_result_tp'] = 'Geteleporteerd',
    ['admin_result_teleport_to_marker'] = 'Je moet een waypoint zetten.',
    ['admin_invalid_vehicle_model'] = 'Ongeldig voertuig model.',
      ['admin_result_freeze'] = 'Je bent gefreezed door een serveradmin.',
      ['admin_result_unfreeze'] = 'Je bent geunfreezed door een serveradmin.',
    ['admin_get_player_coords_result'] = 'De speler %s (%s %s) is bij (%.2f, %.2f, %.2f)',
    ['admin_get_player_coords_error'] = 'Er is een error opgetreden wanneer ik de coördinaten probeerde te vinden.',
    ['admin_get_players'] = '"Speler [%s](%s): %s %s | Ping: %s',
    ['admin_result_killed'] = 'Je bent doodgegaan door een serveradmin.',
      ['admin_result_revive'] = 'Je bent gerevived door een serveradmin.',
      ['admin_result_health'] = 'Je gezondheid is veranderd door een servadmin.',
      ['admin_result_armor'] = 'Je armor is veranderd door een serveradmin.',
    ['admin_result_current_active'] = 'Er is al een actie gaande.',
    ['admin_result_spectate'] = 'Druk op ~INPUT_FRONTEND_CANCEL~ om te stoppen met spectaten.',
  
    -- Unfinished
    -- ['command_kick'] = 'Verwijder',
    -- ['command_ban'] = 'Ban',
    -- ['command_unban'] = 'Unban',
  
    -- Locale settings
    ['locale_digit_grouping_symbol'] = ',',
    ['locale_currency'] = '€%s',
  
    -- Weapons
    ['weapon_knife'] = 'mes',
    ['weapon_nightstick'] = 'gummistok',
    ['weapon_hammer'] = 'hamer',
    ['weapon_bat'] = 'knuppel',
    ['weapon_golfclub'] = 'golfclub',
    ['weapon_crowbar'] = 'koevoet',
    ['weapon_pistol'] = 'pistool',
    ['weapon_combatpistol'] = 'combat pistool',
    ['weapon_appistol'] = 'AP pistool',
    ['weapon_pistol50'] = 'pistool .50',
    ['weapon_microsmg'] = 'micro SMG',
    ['weapon_smg'] = 'SMG',
    ['weapon_assaultsmg'] = 'assault SMG',
    ['weapon_assaultrifle'] = 'assault rifle',
    ['weapon_carbinerifle'] = 'carbine rifle',
    ['weapon_advancedrifle'] = 'advanced rifle',
    ['weapon_mg'] = 'MG',
    ['weapon_combatmg'] = 'combat MG',
    ['weapon_pumpshotgun'] = 'pump shotgun',
    ['weapon_sawnoffshotgun'] = 'sawed off shotgun',
    ['weapon_assaultshotgun'] = 'assault shotgun',
    ['weapon_bullpupshotgun'] = 'bullpup shotgun',
    ['weapon_stungun'] = 'taser',
    ['weapon_sniperrifle'] = 'sniper rifle',
    ['weapon_heavysniper'] = 'heavy sniper',
    ['weapon_grenadelauncher'] = 'granaat launcher',
    ['weapon_rpg'] = 'raket launcher',
    ['weapon_minigun'] = 'minigun',
    ['weapon_grenade'] = 'granaat',
    ['weapon_stickybomb'] = 'kleefbom',
    ['weapon_smokegrenade'] = 'rookgranaat',
    ['weapon_bzgas'] = 'bz gas',
    ['weapon_molotov'] = 'molotov cocktail',
    ['weapon_fireextinguisher'] = 'brandblusser',
    ['weapon_petrolcan'] = 'jerrycan',
    ['weapon_ball'] = 'bal',
    ['weapon_snspistol'] = 'sns pistool',
    ['weapon_bottle'] = 'fles',
    ['weapon_gusenberg'] = 'gusenberg sweeper',
    ['weapon_specialcarbine'] = 'special carbine',
    ['weapon_heavypistol'] = 'heavy pistol',
    ['weapon_bullpuprifle'] = 'bullpup rifle',
    ['weapon_dagger'] = 'dolk',
    ['weapon_vintagepistol'] = 'vintage pistool',
    ['weapon_firework'] = 'vuurwerk',
    ['weapon_musket'] = 'musket',
    ['weapon_heavyshotgun'] = 'heavy shotgun',
    ['weapon_marksmanrifle'] = 'marksman rifle',
    ['weapon_hominglauncher'] = 'homing launcher',
    ['weapon_proxmine'] = 'korteafstandsmijn',
    ['weapon_snowball'] = 'sneeuwbal',
    ['weapon_flaregun'] = 'lichtpistool',
    ['weapon_combatpdw'] = 'combat pdw',
    ['weapon_marksmanpistol'] = 'marksman pistool',
    ['weapon_knuckle'] = 'boksbeugel',
    ['weapon_hatchet'] = 'bijl',
    ['weapon_railgun'] = 'railgun',
    ['weapon_machete'] = 'machete',
    ['weapon_machinepistol'] = 'machinegeweer',
    ['weapon_switchblade'] = 'switchblade',
    ['weapon_revolver'] = 'heavy revolver',
    ['weapon_dbshotgun'] = 'double barrel shotgun',
    ['weapon_compactrifle'] = 'compact rifle',
    ['weapon_autoshotgun'] = 'auto shotgun',
    ['weapon_battleaxe'] = 'strijdbijl',
    ['weapon_compactlauncher'] = 'compact launcher',
    ['weapon_minismg'] = 'mini smg',
    ['weapon_pipebomb'] = 'pijpbom',
    ['weapon_poolcue'] = 'biljartkeu',
    ['weapon_wrench'] = 'tang',
    ['weapon_flashlight'] = 'zaklamp',
    ['gadget_parachute'] = 'parachute',
    ['weapon_flare'] = 'flare',
    ['weapon_doubleaction'] = 'double-Action Revolver',
  
    -- Weapon Components
    ['component_clip_default'] = 'default Clip',
    ['component_clip_extended'] = 'extended Clip',
    ['component_clip_drum'] = 'drum Magazine',
    ['component_clip_box'] = 'box Magazine',
    ['component_flashlight'] = 'zaklamp',
    ['component_scope'] = 'scope',
    ['component_scope_advanced'] = 'advanced Scope',
    ['component_suppressor'] = 'suppressor',
    ['component_grip'] = 'grip',
    ['component_luxary_finish'] = 'luxary Weapon Finish',
  
    -- Weapon Ammo
    ['ammo_rounds'] = 'kogels',
    ['ammo_shells'] = 'kogels',
    ['ammo_charge'] = 'laden',
    ['ammo_petrol'] = 'jerrycan(en)',
    ['ammo_firework'] = 'vuurwerkpijl(len)',
    ['ammo_rockets'] = 'raket(en)',
    ['ammo_grenadelauncher'] = 'granaat(en)',
    ['ammo_grenade'] = 'granaat(en)',
    ['ammo_stickybomb'] = 'bom(en)',
    ['ammo_pipebomb'] = 'bom(en)',
    ['ammo_smokebomb'] = 'bom(en)',
    ['ammo_molotov'] = 'cocktail(s)',
    ['ammo_proxmine'] = 'mijn(en)',
    ['ammo_bzgas'] = 'kan(nen)',
    ['ammo_ball'] = 'bal(len)',
    ['ammo_snowball'] = 'sneeuwbal(len)',
    ['ammo_flare'] = 'flare(s)',
    ['ammo_flaregun'] = 'flare(s)',
  
    -- Weapon Tints
    ['tint_default'] = 'normale skin',
    ['tint_green'] = 'groene skin',
    ['tint_gold'] = 'gouden skin',
    ['tint_pink'] = 'roze skin',
    ['tint_army'] = 'leger skin',
    ['tint_lspd'] = 'blauwe skin',
    ['tint_orange'] = 'oranje skin',
    ['tint_platinum'] = 'platinum skin',
  
    -- Identity
    ['identity_create'] = 'Burger inschrijving',
    ['identity_register'] = 'Registreer je karakter alsjeblieft.',
    ['identity_welcome'] = 'Welkokm, ~b~%s %s',
    ['identity_fill_in'] = 'Vul eerst alle info in voor je het formulier verzend.',
    ['identity_firstname'] = 'Voornaam',
    ['identity_lastname'] = 'Achternaam',
    ['identity_birthdate'] = 'Geboortedatum',
    ['identity_sex'] = "Geslacht",
    ['identity_male'] = "Man",
    ['identity_female'] = "Vrouw",
  
  }
  